CREATE DATABASE skate_shop;

USE skate_shop;

CREATE TABLE MATERIAL (
    ID_MATERIAL INT AUTO_INCREMENT NOT NULL,
    MATERIAL VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID_MATERIAL)
);

CREATE TABLE TECNOLOGIA (
    ID_TECNOLOGIA INT AUTO_INCREMENT NOT NULL,
    TECNOLOGIA VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_TECNOLOGIA)
);

CREATE TABLE TALLA (
    ID_TALLA INT AUTO_INCREMENT NOT NULL,
    TALLA VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_TALLA)
);

CREATE TABLE MARCA (
    ID_MARCA INT AUTO_INCREMENT NOT NULL,
    MARCA VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID_MARCA)
);

CREATE TABLE ENVIO (
    ID_ENVIO INT AUTO_INCREMENT NOT NULL,
    ENVIO VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID_ENVIO)
);

CREATE TABLE CIUDAD (
    ID_CIUDAD INT AUTO_INCREMENT NOT NULL,
    CIUDAD VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID_CIUDAD)
);

CREATE TABLE PAIS (
    ID_PAIS INT AUTO_INCREMENT NOT NULL,
    PAIS VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID_PAIS)
);

CREATE TABLE TIPO_CLIENTE (
    ID_TIPO INT AUTO_INCREMENT NOT NULL,
    TIPO VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID_TIPO)
);

CREATE TABLE CATEGORIA_ARTICULO (
    ID_CAT INT AUTO_INCREMENT NOT NULL,
    CAT_ARTICULO VARCHAR(20),
    PRIMARY KEY (ID_CAT)
);

CREATE TABLE TIPO_PAGO (
    ID_PAGO INT AUTO_INCREMENT NOT NULL,
    TIPO_PAGO VARCHAR(50),
    PRIMARY KEY (ID_PAGO)
);

CREATE TABLE CLIENTE (
    ID_CLIENTE INT AUTO_INCREMENT NOT NULL,
    NOMBRE_CLIENTE VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    ID_PAIS INT NOT NULL,
    ID_CIUDAD INT NOT NULL,
    ID_ENVIO INT NOT NULL,
    PRIMARY KEY(ID_CLIENTE),
    FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS),
    FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD),
    FOREIGN KEY (ID_ENVIO) REFERENCES ENVIO(ID_ENVIO)
);

CREATE TABLE ARTICULO (
    ID_ARTICULO INT AUTO_INCREMENT NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    PRECIO FLOAT NOT NULL,
    COSTO FLOAT NOT NULL,
    ID_CAT INT NOT NULL,
    ID_TALLA INT NOT NULL,
    ID_TECNOLOGIA INT NOT NULL,
    ID_MATERIAL INT NOT NULL,
    PRIMARY KEY(ID_ARTICULO),
    FOREIGN KEY (ID_CAT) REFERENCES CATEGORIA_ARTICULO(ID_CAT),
    FOREIGN KEY (ID_TALLA) REFERENCES TALLA(ID_TALLA),
    FOREIGN KEY (ID_TECNOLOGIA) REFERENCES TECNOLOGIA(ID_TECNOLOGIA),
    FOREIGN KEY (ID_MATERIAL) REFERENCES MATERIAL(ID_MATERIAL)
);

CREATE TABLE FACTURA (
    ID_FACTURA INT AUTO_INCREMENT NOT NULL,
    FACTURA VARCHAR(255),
    FECHA DATE NOT NULL,
    ID_PAGO INT NOT NULL,
    PRIMARY KEY(ID_FACTURA),
    FOREIGN KEY (ID_PAGO) REFERENCES TIPO_PAGO(ID_PAGO)
);

CREATE TABLE FACTURACION (
    ID_VENTA INT AUTO_INCREMENT NOT NULL,
    NUM_FACTURA VARCHAR(255) NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO FLOAT NOT NULL,
    COSTO FLOAT NOT NULL,
    ID_TIPO INT NOT NULL,
    ID_PAGO INT NOT NULL,
    ID_PAIS INT NOT NULL,
    ID_CIUDAD INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    ID_MARCA INT NOT NULL,
    ID_ARTICULO INT NOT NULL,
    ID_FACTURA INT NOT NULL,
    PRIMARY KEY(ID_VENTA),
    FOREIGN KEY (ID_TIPO) REFERENCES TIPO_CLIENTE(ID_TIPO),
    FOREIGN KEY (ID_PAGO) REFERENCES TIPO_PAGO(ID_PAGO),
    FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS),
    FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_MARCA) REFERENCES MARCA(ID_MARCA),
    FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULO(ID_ARTICULO),
    FOREIGN KEY (ID_FACTURA) REFERENCES FACTURA(ID_FACTURA)
);