CREATE DATABASE skate_shop;
USE skate_shop;
CREATE TABLE MATERIAL (
    ID_MATERIAL INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    MATERIAL VARCHAR(100) NOT NULL
) 

CREATE TABLE TECNOLOGIA (
    ID_TECNOLOGIA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    TECNOLOGIA VARCHAR(50) NOT NULL
) 

CREATE TABLE TALLA (
    ID_TALLA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    TALLA VARCHAR(50) NOT NULL
) 

CREATE TABLE MARCA (
    ID_MARCA INT PRIMARY AUTO_INCREMENT KEY NOT NULL,
    MARCA VARCHAR(100) NOT NULL
) 

CREATE TABLE ENVIO (
    ID_ENVIO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ENVIO VARCHAR(100) NOT NULL
) 

CREATE TABLE CUIDAD (
    ID_CIUDAD INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    CIUDAD VARCHAR(100) NOT NULL
) 

CREATE TABLE PAIS (
    ID_PAIS INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    PAIS VARCHAR(100) NOT NULL
) 

CREATE TABLE TIPO_CLIENTE (
    ID_TIPO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    TIPO VARCHAR(100) NOT NULL
) 

CREATE TABLE CATEGORIA_ARTICULO (
    ID_CAT INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    CAT_ARTICULO VARCHAR(20)
) 

CREATE TABLE TIPO_PAGO (
    ID_PAGO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    TIPO_PAGO VARCHAR(50)
)